function sigma_f=stress_SU(x,x1,x2,C_I,P_I,P_I_Re,P_I_Im,A_I,B_I,C_II,P_II,P_II_Re,P_II_Im,A_II,B_II,C_GB,P_GB,P_GB_Re,P_GB_Im,A_GB,B_GB,C_SU,P_SU,P_SU_Re,P_SU_Im,A_SU,B_SU,C_SL,P_SL,P_SL_Re,P_SL_Im,A_SL,B_SL,h,N_app,weights,rho_t_Napp,x_w,C,C0_Cinv,C0_Cinv_C0,b,n,XL1,XL2)

sigma_f=zeros(6,length(x));
for x_quadgk=1:length(x)
    symbols_30_30Napp=zeros(30,30*N_app);
    CH_H=symbols_30_30Napp;
    CI_I=symbols_30_30Napp;
    CH_H0_H=symbols_30_30Napp;
    CI_H0_I=symbols_30_30Napp;
    for i=1:3
        for t=1:3
            for wH=1:N_app
                for alpha=1:3
                    CH_H((i+3),(t-1)*N_app+wH)=CH_H((i+3),(t-1)*N_app+wH)-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,5),P_SL_Im(alpha)*h(1,5));
                    CH_H((i+6),(t-1)*N_app+wH)=CH_H((i+6),(t-1)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1))+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),P_I_Im(alpha)*h(1,1));
                    CH_H((i+9),(t-1)*N_app+wH)=CH_H((i+9),(t-1)*N_app+wH)+Re_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),-P_SU_Im(alpha)*h(1,1))-Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),-P_I_Im(alpha)*h(1,1));
                    CH_H((i+12),(t-1)*N_app+wH)=CH_H((i+12),(t-1)*N_app+wH)-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),P_I_Im(alpha)*h(1,2))+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),P_GB_Im(alpha)*h(1,2));
                    CH_H((i+15),(t-1)*N_app+wH)=CH_H((i+15),(t-1)*N_app+wH)+Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),-P_I_Im(alpha)*h(1,2))-Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),-P_GB_Im(alpha)*h(1,2));
                    CH_H((i+18),(t-1)*N_app+wH)=CH_H((i+18),(t-1)*N_app+wH)-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),P_GB_Im(alpha)*h(1,3))+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),P_II_Im(alpha)*h(1,3));
                    CH_H((i+21),(t-1)*N_app+wH)=CH_H((i+21),(t-1)*N_app+wH)+Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),-P_GB_Im(alpha)*h(1,3))-Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),-P_II_Im(alpha)*h(1,3));
                    CH_H((i+24),(t-1)*N_app+wH)=CH_H((i+24),(t-1)*N_app+wH)-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),P_II_Im(alpha)*h(1,4))+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),P_SL_Im(alpha)*h(1,4));
                    CH_H((i+27),(t-1)*N_app+wH)=CH_H((i+27),(t-1)*N_app+wH)+Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),-P_II_Im(alpha)*h(1,4))-Re_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),-P_SL_Im(alpha)*h(1,4));
                    CH_H((i),(t+2)*N_app+wH)=CH_H((i),(t+2)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1));
                    
                    CH_H((i+3),(t+5)*N_app+wH)=CH_H((i+3),(t+5)*N_app+wH)-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,5),P_SL_Im(alpha)*h(2,5));
                    CH_H((i+12),(t+5)*N_app+wH)=CH_H((i+12),(t+5)*N_app+wH)-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2))+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),P_GB_Im(alpha)*h(2,2));
                    CH_H((i+15),(t+5)*N_app+wH)=CH_H((i+15),(t+5)*N_app+wH)+Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),-P_I_Im(alpha)*h(2,2))-Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),-P_GB_Im(alpha)*h(2,2));
                    CH_H((i+18),(t+5)*N_app+wH)=CH_H((i+18),(t+5)*N_app+wH)-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),P_GB_Im(alpha)*h(2,3))+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),P_II_Im(alpha)*h(2,3));
                    CH_H((i+21),(t+5)*N_app+wH)=CH_H((i+21),(t+5)*N_app+wH)+Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),-P_GB_Im(alpha)*h(2,3))-Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),-P_II_Im(alpha)*h(2,3));
                    CH_H((i+24),(t+5)*N_app+wH)=CH_H((i+24),(t+5)*N_app+wH)-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),P_II_Im(alpha)*h(2,4))+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),P_SL_Im(alpha)*h(2,4));
                    CH_H((i+27),(t+5)*N_app+wH)=CH_H((i+27),(t+5)*N_app+wH)+Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),-P_II_Im(alpha)*h(2,4))-Re_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),-P_SL_Im(alpha)*h(2,4));
                    CH_H((i),(t+8)*N_app+wH)=CH_H((i),(t+8)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,2),P_SU_Im(alpha)*h(1,2));
                    CH_H((i+6),(t+8)*N_app+wH)=CH_H((i+6),(t+8)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    CH_H((i+9),(t+8)*N_app+wH)=CH_H((i+9),(t+8)*N_app+wH)+Re_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))-Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    
                    CH_H((i+3),(t+11)*N_app+wH)=CH_H((i+3),(t+11)*N_app+wH)-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,5),P_SL_Im(alpha)*h(3,5));
                    CH_H((i+18),(t+11)*N_app+wH)=CH_H((i+18),(t+11)*N_app+wH)-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3))+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),P_II_Im(alpha)*h(3,3));
                    CH_H((i+21),(t+11)*N_app+wH)=CH_H((i+21),(t+11)*N_app+wH)+Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),-P_GB_Im(alpha)*h(3,3))-Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),-P_II_Im(alpha)*h(3,3));
                    CH_H((i+24),(t+11)*N_app+wH)=CH_H((i+24),(t+11)*N_app+wH)-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),P_II_Im(alpha)*h(3,4))+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),P_SL_Im(alpha)*h(3,4));
                    CH_H((i+27),(t+11)*N_app+wH)=CH_H((i+27),(t+11)*N_app+wH)+Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),-P_II_Im(alpha)*h(3,4))-Re_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),-P_SL_Im(alpha)*h(3,4));
                    CH_H((i),(t+14)*N_app+wH)=CH_H((i),(t+14)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,3),P_SU_Im(alpha)*h(1,3));
                    CH_H((i+6),(t+14)*N_app+wH)=CH_H((i+6),(t+14)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CH_H((i+9),(t+14)*N_app+wH)=CH_H((i+9),(t+14)*N_app+wH)+Re_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))-Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CH_H((i+12),(t+14)*N_app+wH)=CH_H((i+12),(t+14)*N_app+wH)+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    CH_H((i+15),(t+14)*N_app+wH)=CH_H((i+15),(t+14)*N_app+wH)+Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))-Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    
                    CH_H((i+3),(t+17)*N_app+wH)=CH_H((i+3),(t+17)*N_app+wH)-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,5),P_SL_Im(alpha)*h(4,5));
                    CH_H((i+24),(t+17)*N_app+wH)=CH_H((i+24),(t+17)*N_app+wH)-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4))+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),P_SL_Im(alpha)*h(4,4));
                    CH_H((i+27),(t+17)*N_app+wH)=CH_H((i+27),(t+17)*N_app+wH)+Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),-P_II_Im(alpha)*h(4,4))-Re_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),-P_SL_Im(alpha)*h(4,4));
                    CH_H((i),(t+20)*N_app+wH)=CH_H((i),(t+20)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,4),P_SU_Im(alpha)*h(1,4));
                    CH_H((i+6),(t+20)*N_app+wH)=CH_H((i+6),(t+20)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CH_H((i+9),(t+20)*N_app+wH)=CH_H((i+9),(t+20)*N_app+wH)+Re_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))-Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CH_H((i+12),(t+20)*N_app+wH)=CH_H((i+12),(t+20)*N_app+wH)+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CH_H((i+15),(t+20)*N_app+wH)=CH_H((i+15),(t+20)*N_app+wH)+Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))-Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CH_H((i+18),(t+20)*N_app+wH)=CH_H((i+18),(t+20)*N_app+wH)+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    CH_H((i+21),(t+20)*N_app+wH)=CH_H((i+21),(t+20)*N_app+wH)+Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))-Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    
                    CH_H((i+3),(t+23)*N_app+wH)=CH_H((i+3),(t+23)*N_app+wH)-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CH_H((i),(t+26)*N_app+wH)=CH_H((i),(t+26)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,5),P_SU_Im(alpha)*h(1,5));
                    CH_H((i+6),(t+26)*N_app+wH)=CH_H((i+6),(t+26)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CH_H((i+9),(t+26)*N_app+wH)=CH_H((i+9),(t+26)*N_app+wH)+Re_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))-Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CH_H((i+12),(t+26)*N_app+wH)=CH_H((i+12),(t+26)*N_app+wH)+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CH_H((i+15),(t+26)*N_app+wH)=CH_H((i+15),(t+26)*N_app+wH)+Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))-Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CH_H((i+18),(t+26)*N_app+wH)=CH_H((i+18),(t+26)*N_app+wH)+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CH_H((i+21),(t+26)*N_app+wH)=CH_H((i+21),(t+26)*N_app+wH)+Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))-Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CH_H((i+24),(t+26)*N_app+wH)=CH_H((i+24),(t+26)*N_app+wH)+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CH_H((i+27),(t+26)*N_app+wH)=CH_H((i+27),(t+26)*N_app+wH)+Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))-Re_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    

                    CI_I((i+3),(t-1)*N_app+wH)=CI_I((i+3),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,5),P_SL_Im(alpha)*h(1,5));
                    CI_I((i+6),(t-1)*N_app+wH)=CI_I((i+6),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),P_I_Im(alpha)*h(1,1));
                    CI_I((i+9),(t-1)*N_app+wH)=CI_I((i+9),(t-1)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),-P_SU_Im(alpha)*h(1,1))-Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),-P_I_Im(alpha)*h(1,1));
                    CI_I((i+12),(t-1)*N_app+wH)=CI_I((i+12),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),P_I_Im(alpha)*h(1,2))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),P_GB_Im(alpha)*h(1,2));
                    CI_I((i+15),(t-1)*N_app+wH)=CI_I((i+15),(t-1)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),-P_I_Im(alpha)*h(1,2))-Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),-P_GB_Im(alpha)*h(1,2));
                    CI_I((i+18),(t-1)*N_app+wH)=CI_I((i+18),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),P_GB_Im(alpha)*h(1,3))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),P_II_Im(alpha)*h(1,3));
                    CI_I((i+21),(t-1)*N_app+wH)=CI_I((i+21),(t-1)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),-P_GB_Im(alpha)*h(1,3))-Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),-P_II_Im(alpha)*h(1,3));
                    CI_I((i+24),(t-1)*N_app+wH)=CI_I((i+24),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),P_II_Im(alpha)*h(1,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),P_SL_Im(alpha)*h(1,4));
                    CI_I((i+27),(t-1)*N_app+wH)=CI_I((i+27),(t-1)*N_app+wH)+Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),-P_II_Im(alpha)*h(1,4))-Im_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),-P_SL_Im(alpha)*h(1,4));
                    CI_I((i),(t+2)*N_app+wH)=CI_I((i),(t+2)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1));
                    
                    CI_I((i+3),(t+5)*N_app+wH)=CI_I((i+3),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,5),P_SL_Im(alpha)*h(2,5));
                    CI_I((i+12),(t+5)*N_app+wH)=CI_I((i+12),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),P_GB_Im(alpha)*h(2,2));
                    CI_I((i+15),(t+5)*N_app+wH)=CI_I((i+15),(t+5)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),-P_I_Im(alpha)*h(2,2))-Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),-P_GB_Im(alpha)*h(2,2));
                    CI_I((i+18),(t+5)*N_app+wH)=CI_I((i+18),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),P_GB_Im(alpha)*h(2,3))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),P_II_Im(alpha)*h(2,3));
                    CI_I((i+21),(t+5)*N_app+wH)=CI_I((i+21),(t+5)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),-P_GB_Im(alpha)*h(2,3))-Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),-P_II_Im(alpha)*h(2,3));
                    CI_I((i+24),(t+5)*N_app+wH)=CI_I((i+24),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),P_II_Im(alpha)*h(2,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),P_SL_Im(alpha)*h(2,4));
                    CI_I((i+27),(t+5)*N_app+wH)=CI_I((i+27),(t+5)*N_app+wH)+Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),-P_II_Im(alpha)*h(2,4))-Im_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),-P_SL_Im(alpha)*h(2,4));
                    CI_I((i),(t+8)*N_app+wH)=CI_I((i),(t+8)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,2),P_SU_Im(alpha)*h(1,2));
                    CI_I((i+6),(t+8)*N_app+wH)=CI_I((i+6),(t+8)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    CI_I((i+9),(t+8)*N_app+wH)=CI_I((i+9),(t+8)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))-Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    
                    CI_I((i+3),(t+11)*N_app+wH)=CI_I((i+3),(t+11)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,5),P_SL_Im(alpha)*h(3,5));
                    CI_I((i+18),(t+11)*N_app+wH)=CI_I((i+18),(t+11)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),P_II_Im(alpha)*h(3,3));
                    CI_I((i+21),(t+11)*N_app+wH)=CI_I((i+21),(t+11)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),-P_GB_Im(alpha)*h(3,3))-Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),-P_II_Im(alpha)*h(3,3));
                    CI_I((i+24),(t+11)*N_app+wH)=CI_I((i+24),(t+11)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),P_II_Im(alpha)*h(3,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),P_SL_Im(alpha)*h(3,4));
                    CI_I((i+27),(t+11)*N_app+wH)=CI_I((i+27),(t+11)*N_app+wH)+Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),-P_II_Im(alpha)*h(3,4))-Im_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),-P_SL_Im(alpha)*h(3,4));
                    CI_I((i),(t+14)*N_app+wH)=CI_I((i),(t+14)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,3),P_SU_Im(alpha)*h(1,3));
                    CI_I((i+6),(t+14)*N_app+wH)=CI_I((i+6),(t+14)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CI_I((i+9),(t+14)*N_app+wH)=CI_I((i+9),(t+14)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))-Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CI_I((i+12),(t+14)*N_app+wH)=CI_I((i+12),(t+14)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    CI_I((i+15),(t+14)*N_app+wH)=CI_I((i+15),(t+14)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))-Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    
                    CI_I((i+3),(t+17)*N_app+wH)=CI_I((i+3),(t+17)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,5),P_SL_Im(alpha)*h(4,5));
                    CI_I((i+24),(t+17)*N_app+wH)=CI_I((i+24),(t+17)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),P_SL_Im(alpha)*h(4,4));
                    CI_I((i+27),(t+17)*N_app+wH)=CI_I((i+27),(t+17)*N_app+wH)+Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),-P_II_Im(alpha)*h(4,4))-Im_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),-P_SL_Im(alpha)*h(4,4));
                    CI_I((i),(t+20)*N_app+wH)=CI_I((i),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,4),P_SU_Im(alpha)*h(1,4));
                    CI_I((i+6),(t+20)*N_app+wH)=CI_I((i+6),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CI_I((i+9),(t+20)*N_app+wH)=CI_I((i+9),(t+20)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))-Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CI_I((i+12),(t+20)*N_app+wH)=CI_I((i+12),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CI_I((i+15),(t+20)*N_app+wH)=CI_I((i+15),(t+20)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))-Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CI_I((i+18),(t+20)*N_app+wH)=CI_I((i+18),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    CI_I((i+21),(t+20)*N_app+wH)=CI_I((i+21),(t+20)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))-Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    
                    CI_I((i+3),(t+23)*N_app+wH)=CI_I((i+3),(t+23)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CI_I((i),(t+26)*N_app+wH)=CI_I((i),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,5),P_SU_Im(alpha)*h(1,5));
                    CI_I((i+6),(t+26)*N_app+wH)=CI_I((i+6),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CI_I((i+9),(t+26)*N_app+wH)=CI_I((i+9),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))-Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CI_I((i+12),(t+26)*N_app+wH)=CI_I((i+12),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CI_I((i+15),(t+26)*N_app+wH)=CI_I((i+15),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))-Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CI_I((i+18),(t+26)*N_app+wH)=CI_I((i+18),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CI_I((i+21),(t+26)*N_app+wH)=CI_I((i+21),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))-Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CI_I((i+24),(t+26)*N_app+wH)=CI_I((i+24),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CI_I((i+27),(t+26)*N_app+wH)=CI_I((i+27),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))-Im_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    

                    CH_H0_H((i+3),(t-1)*N_app+wH)=CH_H0_H((i+3),(t-1)*N_app+wH)+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,5),P_SL_Im(alpha)*h(1,5));
                    CH_H0_H((i+6),(t-1)*N_app+wH)=CH_H0_H((i+6),(t-1)*N_app+wH)+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1))-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),P_I_Im(alpha)*h(1,1));
                    CH_H0_H((i+9),(t-1)*N_app+wH)=CH_H0_H((i+9),(t-1)*N_app+wH)-Re_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1))+Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),P_I_Im(alpha)*h(1,1));
                    CH_H0_H((i+12),(t-1)*N_app+wH)=CH_H0_H((i+12),(t-1)*N_app+wH)+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),P_I_Im(alpha)*h(1,2))-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),P_GB_Im(alpha)*h(1,2));
                    CH_H0_H((i+15),(t-1)*N_app+wH)=CH_H0_H((i+15),(t-1)*N_app+wH)-Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),P_I_Im(alpha)*h(1,2))+Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),P_GB_Im(alpha)*h(1,2));
                    CH_H0_H((i+18),(t-1)*N_app+wH)=CH_H0_H((i+18),(t-1)*N_app+wH)+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),P_GB_Im(alpha)*h(1,3))-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),P_II_Im(alpha)*h(1,3));
                    CH_H0_H((i+21),(t-1)*N_app+wH)=CH_H0_H((i+21),(t-1)*N_app+wH)-Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),P_GB_Im(alpha)*h(1,3))+Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),P_II_Im(alpha)*h(1,3));
                    CH_H0_H((i+24),(t-1)*N_app+wH)=CH_H0_H((i+24),(t-1)*N_app+wH)+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),P_II_Im(alpha)*h(1,4))-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),P_SL_Im(alpha)*h(1,4));
                    CH_H0_H((i+27),(t-1)*N_app+wH)=CH_H0_H((i+27),(t-1)*N_app+wH)-Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),P_II_Im(alpha)*h(1,4))+Re_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),P_SL_Im(alpha)*h(1,4));
                    CH_H0_H((i),(t+2)*N_app+wH)=CH_H0_H((i),(t+2)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1));
                    
                    CH_H0_H((i+3),(t+5)*N_app+wH)=CH_H0_H((i+3),(t+5)*N_app+wH)+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,5),P_SL_Im(alpha)*h(2,5));
                    CH_H0_H((i+12),(t+5)*N_app+wH)=CH_H0_H((i+12),(t+5)*N_app+wH)+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2))-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),P_GB_Im(alpha)*h(2,2));
                    CH_H0_H((i+15),(t+5)*N_app+wH)=CH_H0_H((i+15),(t+5)*N_app+wH)-Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2))+Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),P_GB_Im(alpha)*h(2,2));
                    CH_H0_H((i+18),(t+5)*N_app+wH)=CH_H0_H((i+18),(t+5)*N_app+wH)+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),P_GB_Im(alpha)*h(2,3))-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),P_II_Im(alpha)*h(2,3));
                    CH_H0_H((i+21),(t+5)*N_app+wH)=CH_H0_H((i+21),(t+5)*N_app+wH)-Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),P_GB_Im(alpha)*h(2,3))+Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),P_II_Im(alpha)*h(2,3));
                    CH_H0_H((i+24),(t+5)*N_app+wH)=CH_H0_H((i+24),(t+5)*N_app+wH)+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),P_II_Im(alpha)*h(2,4))-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),P_SL_Im(alpha)*h(2,4));
                    CH_H0_H((i+27),(t+5)*N_app+wH)=CH_H0_H((i+27),(t+5)*N_app+wH)-Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),P_II_Im(alpha)*h(2,4))+Re_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),P_SL_Im(alpha)*h(2,4));
                    CH_H0_H((i),(t+8)*N_app+wH)=CH_H0_H((i),(t+8)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,2),P_SU_Im(alpha)*h(1,2));
                    CH_H0_H((i+6),(t+8)*N_app+wH)=CH_H0_H((i+6),(t+8)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    CH_H0_H((i+9),(t+8)*N_app+wH)=CH_H0_H((i+9),(t+8)*N_app+wH)-Re_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))+Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    
                    CH_H0_H((i+3),(t+11)*N_app+wH)=CH_H0_H((i+3),(t+11)*N_app+wH)+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,5),P_SL_Im(alpha)*h(3,5));
                    CH_H0_H((i+18),(t+11)*N_app+wH)=CH_H0_H((i+18),(t+11)*N_app+wH)+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3))-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),P_II_Im(alpha)*h(3,3));
                    CH_H0_H((i+21),(t+11)*N_app+wH)=CH_H0_H((i+21),(t+11)*N_app+wH)-Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3))+Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),P_II_Im(alpha)*h(3,3));
                    CH_H0_H((i+24),(t+11)*N_app+wH)=CH_H0_H((i+24),(t+11)*N_app+wH)+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),P_II_Im(alpha)*h(3,4))-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),P_SL_Im(alpha)*h(3,4));
                    CH_H0_H((i+27),(t+11)*N_app+wH)=CH_H0_H((i+27),(t+11)*N_app+wH)-Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),P_II_Im(alpha)*h(3,4))+Re_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),P_SL_Im(alpha)*h(3,4));
                    CH_H0_H((i),(t+14)*N_app+wH)=CH_H0_H((i),(t+14)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,3),P_SU_Im(alpha)*h(1,3));
                    CH_H0_H((i+6),(t+14)*N_app+wH)=CH_H0_H((i+6),(t+14)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CH_H0_H((i+9),(t+14)*N_app+wH)=CH_H0_H((i+9),(t+14)*N_app+wH)-Re_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))+Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CH_H0_H((i+12),(t+14)*N_app+wH)=CH_H0_H((i+12),(t+14)*N_app+wH)-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    CH_H0_H((i+15),(t+14)*N_app+wH)=CH_H0_H((i+15),(t+14)*N_app+wH)-Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))+Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    
                    CH_H0_H((i+3),(t+17)*N_app+wH)=CH_H0_H((i+3),(t+17)*N_app+wH)+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,5),P_SL_Im(alpha)*h(4,5));
                    CH_H0_H((i+24),(t+17)*N_app+wH)=CH_H0_H((i+24),(t+17)*N_app+wH)+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4))-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),P_SL_Im(alpha)*h(4,4));
                    CH_H0_H((i+27),(t+17)*N_app+wH)=CH_H0_H((i+27),(t+17)*N_app+wH)-Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4))+Re_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),P_SL_Im(alpha)*h(4,4));
                    CH_H0_H((i),(t+20)*N_app+wH)=CH_H0_H((i),(t+20)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,4),P_SU_Im(alpha)*h(1,4));
                    CH_H0_H((i+6),(t+20)*N_app+wH)=CH_H0_H((i+6),(t+20)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CH_H0_H((i+9),(t+20)*N_app+wH)=CH_H0_H((i+9),(t+20)*N_app+wH)-Re_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))+Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CH_H0_H((i+12),(t+20)*N_app+wH)=CH_H0_H((i+12),(t+20)*N_app+wH)-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CH_H0_H((i+15),(t+20)*N_app+wH)=CH_H0_H((i+15),(t+20)*N_app+wH)-Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))+Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CH_H0_H((i+18),(t+20)*N_app+wH)=CH_H0_H((i+18),(t+20)*N_app+wH)-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    CH_H0_H((i+21),(t+20)*N_app+wH)=CH_H0_H((i+21),(t+20)*N_app+wH)-Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))+Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    
                    CH_H0_H((i+3),(t+23)*N_app+wH)=CH_H0_H((i+3),(t+23)*N_app+wH)+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CH_H0_H((i),(t+26)*N_app+wH)=CH_H0_H((i),(t+26)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,5),P_SU_Im(alpha)*h(1,5));
                    CH_H0_H((i+6),(t+26)*N_app+wH)=CH_H0_H((i+6),(t+26)*N_app+wH)-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))+Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CH_H0_H((i+9),(t+26)*N_app+wH)=CH_H0_H((i+9),(t+26)*N_app+wH)-Re_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))+Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CH_H0_H((i+12),(t+26)*N_app+wH)=CH_H0_H((i+12),(t+26)*N_app+wH)-Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))+Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CH_H0_H((i+15),(t+26)*N_app+wH)=CH_H0_H((i+15),(t+26)*N_app+wH)-Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))+Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CH_H0_H((i+18),(t+26)*N_app+wH)=CH_H0_H((i+18),(t+26)*N_app+wH)-Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))+Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CH_H0_H((i+21),(t+26)*N_app+wH)=CH_H0_H((i+21),(t+26)*N_app+wH)-Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))+Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CH_H0_H((i+24),(t+26)*N_app+wH)=CH_H0_H((i+24),(t+26)*N_app+wH)-Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CH_H0_H((i+27),(t+26)*N_app+wH)=CH_H0_H((i+27),(t+26)*N_app+wH)-Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))+Re_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));

                    
                    CI_H0_I((i+3),(t-1)*N_app+wH)=CI_H0_I((i+3),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,5),P_SL_Im(alpha)*h(1,5));
                    CI_H0_I((i+6),(t-1)*N_app+wH)=CI_H0_I((i+6),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),P_I_Im(alpha)*h(1,1));
                    CI_H0_I((i+9),(t-1)*N_app+wH)=CI_H0_I((i+9),(t-1)*N_app+wH)-Im_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),-P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1))+Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,1),P_I_Im(alpha)*h(1,1));
                    CI_H0_I((i+12),(t-1)*N_app+wH)=CI_H0_I((i+12),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),P_I_Im(alpha)*h(1,2))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),P_GB_Im(alpha)*h(1,2));
                    CI_H0_I((i+15),(t-1)*N_app+wH)=CI_H0_I((i+15),(t-1)*N_app+wH)-Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(1,2),P_I_Im(alpha)*h(1,2))+Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,2),P_GB_Im(alpha)*h(1,2));
                    CI_H0_I((i+18),(t-1)*N_app+wH)=CI_H0_I((i+18),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),P_GB_Im(alpha)*h(1,3))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),P_II_Im(alpha)*h(1,3));
                    CI_H0_I((i+21),(t-1)*N_app+wH)=CI_H0_I((i+21),(t-1)*N_app+wH)-Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(1,3),P_GB_Im(alpha)*h(1,3))+Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,3),P_II_Im(alpha)*h(1,3));
                    CI_H0_I((i+24),(t-1)*N_app+wH)=CI_H0_I((i+24),(t-1)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),P_II_Im(alpha)*h(1,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),P_SL_Im(alpha)*h(1,4));
                    CI_H0_I((i+27),(t-1)*N_app+wH)=CI_H0_I((i+27),(t-1)*N_app+wH)-Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(1,4),P_II_Im(alpha)*h(1,4))+Im_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(1,4),P_SL_Im(alpha)*h(1,4));
                    CI_H0_I((i),(t+2)*N_app+wH)=CI_H0_I((i),(t+2)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,1),P_SU_Im(alpha)*h(1,1));
                    
                    CI_H0_I((i+3),(t+5)*N_app+wH)=CI_H0_I((i+3),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,5),P_SL_Im(alpha)*h(2,5));
                    CI_H0_I((i+12),(t+5)*N_app+wH)=CI_H0_I((i+12),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),P_GB_Im(alpha)*h(2,2));
                    CI_H0_I((i+15),(t+5)*N_app+wH)=CI_H0_I((i+15),(t+5)*N_app+wH)-Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),-P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2))+Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,2),P_GB_Im(alpha)*h(2,2));
                    CI_H0_I((i+18),(t+5)*N_app+wH)=CI_H0_I((i+18),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),P_GB_Im(alpha)*h(2,3))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),P_II_Im(alpha)*h(2,3));
                    CI_H0_I((i+21),(t+5)*N_app+wH)=CI_H0_I((i+21),(t+5)*N_app+wH)-Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(2,3),P_GB_Im(alpha)*h(2,3))+Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,3),P_II_Im(alpha)*h(2,3));
                    CI_H0_I((i+24),(t+5)*N_app+wH)=CI_H0_I((i+24),(t+5)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),P_II_Im(alpha)*h(2,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),P_SL_Im(alpha)*h(2,4));
                    CI_H0_I((i+27),(t+5)*N_app+wH)=CI_H0_I((i+27),(t+5)*N_app+wH)-Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(2,4),P_II_Im(alpha)*h(2,4))+Im_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(2,4),P_SL_Im(alpha)*h(2,4));
                    CI_H0_I((i),(t+8)*N_app+wH)=CI_H0_I((i),(t+8)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,2),P_SU_Im(alpha)*h(1,2));
                    CI_H0_I((i+6),(t+8)*N_app+wH)=CI_H0_I((i+6),(t+8)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    CI_H0_I((i+9),(t+8)*N_app+wH)=CI_H0_I((i+9),(t+8)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,2),P_SU_Im(alpha)*h(2,2))-Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,2),P_I_Im(alpha)*h(2,2));
                    
                    CI_H0_I((i+3),(t+11)*N_app+wH)=CI_H0_I((i+3),(t+11)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,5),P_SL_Im(alpha)*h(3,5));
                    CI_H0_I((i+18),(t+11)*N_app+wH)=CI_H0_I((i+18),(t+11)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),P_II_Im(alpha)*h(3,3));
                    CI_H0_I((i+21),(t+11)*N_app+wH)=CI_H0_I((i+21),(t+11)*N_app+wH)-Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),-P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3))+Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,3),P_II_Im(alpha)*h(3,3));
                    CI_H0_I((i+24),(t+11)*N_app+wH)=CI_H0_I((i+24),(t+11)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),P_II_Im(alpha)*h(3,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),P_SL_Im(alpha)*h(3,4));
                    CI_H0_I((i+27),(t+11)*N_app+wH)=CI_H0_I((i+27),(t+11)*N_app+wH)-Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(3,4),P_II_Im(alpha)*h(3,4))+Im_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(3,4),P_SL_Im(alpha)*h(3,4));
                    CI_H0_I((i),(t+14)*N_app+wH)=CI_H0_I((i),(t+14)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,3),P_SU_Im(alpha)*h(1,3));
                    CI_H0_I((i+6),(t+14)*N_app+wH)=CI_H0_I((i+6),(t+14)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CI_H0_I((i+9),(t+14)*N_app+wH)=CI_H0_I((i+9),(t+14)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,3),P_SU_Im(alpha)*h(2,3))-Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,3),P_I_Im(alpha)*h(2,3));
                    CI_H0_I((i+12),(t+14)*N_app+wH)=CI_H0_I((i+12),(t+14)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    CI_H0_I((i+15),(t+14)*N_app+wH)=CI_H0_I((i+15),(t+14)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,3),P_I_Im(alpha)*h(3,3))-Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,3),P_GB_Im(alpha)*h(3,3));
                    
                    CI_H0_I((i+3),(t+17)*N_app+wH)=CI_H0_I((i+3),(t+17)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,5),P_SL_Im(alpha)*h(4,5));
                    CI_H0_I((i+24),(t+17)*N_app+wH)=CI_H0_I((i+24),(t+17)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),P_SL_Im(alpha)*h(4,4));
                    CI_H0_I((i+27),(t+17)*N_app+wH)=CI_H0_I((i+27),(t+17)*N_app+wH)-Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),-P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4))+Im_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(4,4),P_SL_Im(alpha)*h(4,4));
                    CI_H0_I((i),(t+20)*N_app+wH)=CI_H0_I((i),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,4),P_SU_Im(alpha)*h(1,4));
                    CI_H0_I((i+6),(t+20)*N_app+wH)=CI_H0_I((i+6),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CI_H0_I((i+9),(t+20)*N_app+wH)=CI_H0_I((i+9),(t+20)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,4),P_SU_Im(alpha)*h(2,4))-Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,4),P_I_Im(alpha)*h(2,4));
                    CI_H0_I((i+12),(t+20)*N_app+wH)=CI_H0_I((i+12),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CI_H0_I((i+15),(t+20)*N_app+wH)=CI_H0_I((i+15),(t+20)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,4),P_I_Im(alpha)*h(3,4))-Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,4),P_GB_Im(alpha)*h(3,4));
                    CI_H0_I((i+18),(t+20)*N_app+wH)=CI_H0_I((i+18),(t+20)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    CI_H0_I((i+21),(t+20)*N_app+wH)=CI_H0_I((i+21),(t+20)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,4),P_GB_Im(alpha)*h(4,4))-Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,4),P_II_Im(alpha)*h(4,4));
                    
                    CI_H0_I((i+3),(t+23)*N_app+wH)=CI_H0_I((i+3),(t+23)*N_app+wH)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),-P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5)); 
                    CI_H0_I((i),(t+26)*N_app+wH)=CI_H0_I((i),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(1,5),P_SU_Im(alpha)*h(1,5));
                    CI_H0_I((i+6),(t+26)*N_app+wH)=CI_H0_I((i+6),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CI_H0_I((i+9),(t+26)*N_app+wH)=CI_H0_I((i+9),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),x_w(wH),P_SU_Re(alpha)*h(2,5),P_SU_Im(alpha)*h(2,5))-Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(2,5),P_I_Im(alpha)*h(2,5));
                    CI_H0_I((i+12),(t+26)*N_app+wH)=CI_H0_I((i+12),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CI_H0_I((i+15),(t+26)*N_app+wH)=CI_H0_I((i+15),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),x_w(wH),P_I_Re(alpha)*h(3,5),P_I_Im(alpha)*h(3,5))-Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(3,5),P_GB_Im(alpha)*h(3,5));
                    CI_H0_I((i+18),(t+26)*N_app+wH)=CI_H0_I((i+18),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CI_H0_I((i+21),(t+26)*N_app+wH)=CI_H0_I((i+21),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),x_w(wH),P_GB_Re(alpha)*h(4,5),P_GB_Im(alpha)*h(4,5))-Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(4,5),P_II_Im(alpha)*h(4,5));
                    CI_H0_I((i+24),(t+26)*N_app+wH)=CI_H0_I((i+24),(t+26)*N_app+wH)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));
                    CI_H0_I((i+27),(t+26)*N_app+wH)=CI_H0_I((i+27),(t+26)*N_app+wH)+Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),x_w(wH),P_II_Re(alpha)*h(5,5),P_II_Im(alpha)*h(5,5))-Im_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),x_w(wH),P_SL_Re(alpha)*h(5,5),P_SL_Im(alpha)*h(5,5));                    
                end 
            end 
        end
    end
    CH_H=2*CH_H;
    CI_I=2*CI_I;
    CH_H0_H=2*CH_H0_H;
    CI_H0_I=2*CI_H0_I;
%%
    rho_t=zeros(30,1);
    for n_dis=1:n
        symbols_30_3=zeros(30,3);
        CR_R=symbols_30_3;
        CR_H0_R=symbols_30_3;
        for i=1:3
            for t=1:3
                for alpha=1:3
                    CR_R(i,t)=CR_R(i,t)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),XL1(n_dis),-P_SU_Re(alpha)*XL2(n_dis),-P_SU_Im(alpha)*XL2(n_dis))+Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),XL1(n_dis),-P_SU_Re(alpha)*XL2(n_dis),-P_SU_Im(alpha)*XL2(n_dis));
                    CR_R(i+3,t)=CR_R(i+3,t)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,5)-XL2(n_dis)),-P_SL_Im(alpha)*(-h(1,5)-XL2(n_dis)))-Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,5)-XL2(n_dis)),-P_SL_Im(alpha)*(-h(1,5)-XL2(n_dis)));
                    CR_R(i+6,t)=CR_R(i+6,t)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis))))+sign(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis))))-sign(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis)))); 
                    CR_R(i+9,t)=CR_R(i+9,t)+Re_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis)))+Im_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis)))-Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),P_I_Im(alpha)*(-h(1,1)-XL2(n_dis)))-Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),P_I_Im(alpha)*(-h(1,1)-XL2(n_dis)));
                    CR_R(i+12,t)=CR_R(i+12,t)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis))))+sign(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis))))-sign(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis))));
                    CR_R(i+15,t)=CR_R(i+15,t)+Re_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),P_I_Im(alpha)*(-h(1,2)-XL2(n_dis)))+Im_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),P_I_Im(alpha)*(-h(1,2)-XL2(n_dis)))-Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis)))-Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis)));
                    CR_R(i+18,t)=CR_R(i+18,t)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis))))+sign(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis))))-sign(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis))));
                    CR_R(i+21,t)=CR_R(i+21,t)+Re_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis)))+Im_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis)))-Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),P_II_Im(alpha)*(-h(1,3)-XL2(n_dis)))-Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),P_II_Im(alpha)*(-h(1,3)-XL2(n_dis)));
                    CR_R(i+24,t)=CR_R(i+24,t)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis))))+sign(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis))))-sign(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis)))); 
                    CR_R(i+27,t)=CR_R(i+27,t)+Re_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),P_II_Im(alpha)*(-h(1,4)-XL2(n_dis)))+Im_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),P_II_Im(alpha)*(-h(1,4)-XL2(n_dis)))-Re_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis)))-Im_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis)));

                    CR_H0_R(i,t)=CR_H0_R(i,t)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),XL1(n_dis),-P_SU_Re(alpha)*XL2(n_dis),-P_SU_Im(alpha)*XL2(n_dis))-Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),XL1(n_dis),-P_SU_Re(alpha)*XL2(n_dis),-P_SU_Im(alpha)*XL2(n_dis));
                    CR_H0_R(i+3,t)=CR_H0_R(i+3,t)-Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,5)-XL2(n_dis)),-P_SL_Im(alpha)*(-h(1,5)-XL2(n_dis)))+Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,5)-XL2(n_dis)),-P_SL_Im(alpha)*(-h(1,5)-XL2(n_dis)));
                    CR_H0_R(i+6,t)=CR_H0_R(i+6,t)-Re_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*P_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis))))-sign(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_SU,P_SU,A_SU,B_SU)*Q_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis))))+sign(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis))));
                    CR_H0_R(i+9,t)=CR_H0_R(i+9,t)-Re_Zeta(t,alpha,i,A_SU,B_SU)*Q_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis))))+sign(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_SU,B_SU)*P_R(x(x_quadgk),XL1(n_dis),P_SU_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_SU_Im(alpha)*(-h(1,1)-XL2(n_dis))))+Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis))))-sign(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,1)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,1)-XL2(n_dis))));
                    CR_H0_R(i+12,t)=CR_H0_R(i+12,t)-Re_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis))))-sign(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_I,P_I,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis))))+sign(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis)))); 
                    CR_H0_R(i+15,t)=CR_H0_R(i+15,t)-Re_Zeta(t,alpha,i,A_I,B_I)*Q_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis))))+sign(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_I,B_I)*P_R(x(x_quadgk),XL1(n_dis),P_I_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_I_Im(alpha)*(-h(1,2)-XL2(n_dis))))+Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis))))-sign(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,2)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,2)-XL2(n_dis))));
                    CR_H0_R(i+18,t)=CR_H0_R(i+18,t)-Re_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis))))-sign(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_GB,P_GB,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis))))+sign(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis))));
                    CR_H0_R(i+21,t)=CR_H0_R(i+21,t)-Re_Zeta(t,alpha,i,A_GB,B_GB)*Q_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis))))+sign(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_GB,B_GB)*P_R(x(x_quadgk),XL1(n_dis),P_GB_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_GB_Im(alpha)*(-h(1,3)-XL2(n_dis))))+Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis))))-sign(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,3)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,3)-XL2(n_dis)))); 
                    CR_H0_R(i+24,t)=CR_H0_R(i+24,t)-Re_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis))))-sign(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_II,P_II,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis))))+Re_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*P_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis))))+sign(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis)))*Im_Xi(t,alpha,i,C_SL,P_SL,A_SL,B_SL)*Q_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis))));
                    CR_H0_R(i+27,t)=CR_H0_R(i+27,t)-Re_Zeta(t,alpha,i,A_II,B_II)*Q_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis))))+sign(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_II,B_II)*P_R(x(x_quadgk),XL1(n_dis),P_II_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_II_Im(alpha)*(-h(1,4)-XL2(n_dis))))+Re_Zeta(t,alpha,i,A_SL,B_SL)*Q_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis))))-sign(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis)))*Im_Zeta(t,alpha,i,A_SL,B_SL)*P_R(x(x_quadgk),XL1(n_dis),P_SL_Re(alpha)*(-h(1,4)-XL2(n_dis)),abs(P_SL_Im(alpha)*(-h(1,4)-XL2(n_dis))));                
                end
            end
        end
        CR_R=2*CR_R;
        CR_H0_R=2*CR_H0_R;

        coff=(C+C0_Cinv_C0)\diag(ones(1,30));
        rho_t=rho_t+coff*(-(CH_H+CI_I-C0_Cinv*CH_H0_H-C0_Cinv*CI_H0_I)*weights*rho_t_Napp(:,n_dis)+(-CR_R+C0_Cinv*CR_H0_R)*b);
    end 
    
    rho_1U=rho_t(1:3,1);
    rho_1L=rho_t(4:6,1);
    rho_2L=rho_t(10:12,1);
    rho_3L=rho_t(16:18,1);
    rho_4L=rho_t(22:24,1);
    rho_5L=rho_t(28:30,1);
%%
    symbols_3_3=zeros(3,3);
    sigma_1U_exp=symbols_3_3;
    sigma_1L_exp=symbols_3_3;
    sigma_2L_exp=symbols_3_3;
    sigma_3L_exp=symbols_3_3;
    sigma_4L_exp=symbols_3_3;
    sigma_5L_exp=symbols_3_3;

    for i=1:3
        for j=1:2
            for t=1:3
                for alpha=1:3
                    sigma_1U_exp(i,j)=sigma_1U_exp(i,j)+2*(Re_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*P_R(x1,x(x_quadgk),P_SU_Re(alpha)*x2,P_SU_Im(alpha)*x2)+Im_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*Q_R(x1,x(x_quadgk),P_SU_Re(alpha)*x2,P_SU_Im(alpha)*x2))*rho_1U(t);
                    sigma_1L_exp(i,j)=sigma_1L_exp(i,j)+2*(Re_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*P_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,1)),P_SU_Im(alpha)*(x2+h(1,1)))+Im_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*Q_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,1)),P_SU_Im(alpha)*(x2+h(1,1))))*rho_1L(t);
                    sigma_2L_exp(i,j)=sigma_2L_exp(i,j)+2*(Re_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*P_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,2)),P_SU_Im(alpha)*(x2+h(1,2)))+Im_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*Q_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,2)),P_SU_Im(alpha)*(x2+h(1,2))))*rho_2L(t);
                    sigma_3L_exp(i,j)=sigma_3L_exp(i,j)+2*(Re_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*P_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,3)),P_SU_Im(alpha)*(x2+h(1,3)))+Im_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*Q_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,3)),P_SU_Im(alpha)*(x2+h(1,3))))*rho_3L(t);
                    sigma_4L_exp(i,j)=sigma_4L_exp(i,j)+2*(Re_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*P_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,4)),P_SU_Im(alpha)*(x2+h(1,4)))+Im_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*Q_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,4)),P_SU_Im(alpha)*(x2+h(1,4))))*rho_4L(t);
                    sigma_5L_exp(i,j)=sigma_5L_exp(i,j)+2*(Re_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*P_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,5)),P_SU_Im(alpha)*(x2+h(1,5)))+Im_Zeta_S(t,alpha,i,j,P_SU,A_SU,B_SU)*Q_R(x1,x(x_quadgk),P_SU_Re(alpha)*(x2+h(1,5)),P_SU_Im(alpha)*(x2+h(1,5))))*rho_5L(t);
                end 
            end 
        end 
    end 

%%
    sigma_f(1,x_quadgk)=sigma_1U_exp(1,1)+sigma_1L_exp(1,1)+sigma_2L_exp(1,1)+sigma_3L_exp(1,1)+sigma_4L_exp(1,1)+sigma_5L_exp(1,1);
    sigma_f(2,x_quadgk)=sigma_1U_exp(2,1)+sigma_1L_exp(2,1)+sigma_2L_exp(2,1)+sigma_3L_exp(2,1)+sigma_4L_exp(2,1)+sigma_5L_exp(2,1);
    sigma_f(3,x_quadgk)=sigma_1U_exp(3,1)+sigma_1L_exp(3,1)+sigma_2L_exp(3,1)+sigma_3L_exp(3,1)+sigma_4L_exp(3,1)+sigma_5L_exp(3,1);
    sigma_f(4,x_quadgk)=sigma_1U_exp(1,2)+sigma_1L_exp(1,2)+sigma_2L_exp(1,2)+sigma_3L_exp(1,2)+sigma_4L_exp(1,2)+sigma_5L_exp(1,2);
    sigma_f(5,x_quadgk)=sigma_1U_exp(2,2)+sigma_1L_exp(2,2)+sigma_2L_exp(2,2)+sigma_3L_exp(2,2)+sigma_4L_exp(2,2)+sigma_5L_exp(2,2);
    sigma_f(6,x_quadgk)=sigma_1U_exp(3,2)+sigma_1L_exp(3,2)+sigma_2L_exp(3,2)+sigma_3L_exp(3,2)+sigma_4L_exp(3,2)+sigma_5L_exp(3,2);
end
 

